"""create routes table

Revision ID: 1799784f3c13
Revises: 20260525_0002
Create Date: 2026-05-26 17:50:10.839400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1799784f3c13'
down_revision: Union[str, None] = '20260525_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
